version = 1
SPDX-PackageName = "ChangelogAutomation"
SPDX-PackageSupplier = "Friedrich von Never <friedrich@fornever.me>"
SPDX-PackageDownloadLocation = "https://github.com/ForNeVeR/ChangelogAutomation"

[[annotations]]
path = ".idea/**/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2025 Friedrich von Never <friedrich@fornever.me>"
SPDX-License-Identifier = "MIT"
